### PR TITLE
Link against LibRT on older Linux distros

### PR DESCRIPTION
**Pull request by rovinski**
Fix for The-OpenROAD-Project/OpenROAD-flow-scripts#64

See [here](https://stackoverflow.com/questions/2418157/c-error-undefined-reference-to-clock-gettime-and-clock-settime/32649327#32649327) for explanation

### CODE REVIEW

**Comment by yashton** [comment]
Given that this is currently working outside of RHEL 6, is it possible to be more targeted in the conditions to only include this on that OS?

**Comment by rovinski** [comment]
We had this problem in [OpenROAD](https://github.com/The-OpenROAD-Project) quite a while ago and [this](https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/src/CMakeLists.txt#L263-L270) was the fix that we inserted. I did look it up but there really isn't a low-overhead way of checking the glibc version short of creating a custom cmake function to use [an external program](https://stackoverflow.com/questions/9705660/check-glibc-version-for-a-particular-gcc-compiler). Here's [one way someone did it](https://gist.github.com/likema/f5c04dad837d2f5068ae7a8860c180e7).

If you prefer the more-work but more-specialized approach of getting the glibc version, I can do that instead. We preferred the former in OpenROAD because linking libRT when not needed is rather harmless.

**Comment by yashton** [comment]
> linking libRT when not needed is rather harmless.

Works for me

**Review by yashton — APPROVED** [review]

**Comment by rovinski** [comment]
I'm guessing the CI won't get triggered until someone starts it manually?

**Comment by yashton** [comment]
I have no idea why the checks aren't running. I've just manually merged it.

**Pull request merged**
