### PR TITLE
Changes to support inclusion in OpenROAD

### PR DESCRIPTION
**Pull request by yashton**

### CODE REVIEW

**Review by srtemp — COMMENTED** [review]
Dockerfile.debian.testing and Dockerfile.ubuntu.bionic differ only by cmake and readline versions.  Is that the intent? Do we need both?

**Comment by mithro** [comment]
BTW - Rather than generating your own containers, it would be really awesome if LSOracle was packaged and included in the containers generated by https://github.com/hdl/containers (@umarcor).

**Review by srtemp — APPROVED** [review]
Dockerfile comments aside, it looks good and builds.

**Comment by srtemp** [comment]
> BTW - Rather than generating your own containers, it would be really awesome if LSOracle was packaged and included in the containers generated by https://github.com/hdl/containers (@umarcor).

Saw this right as I was hitting approve; thanks for pointing us to those, that's a good idea.

**Comment by yashton** [comment]
> Dockerfile.debian.testing and Dockerfile.ubuntu.bionic differ only by cmake and readline versions. Is that the intent? Do we need both?
It's not particularly worth it to try and generate or abstract the dockerfiles. I would say this is a case of things being very simliar but not the same.

**Comment by umarcor** [comment]
> > Dockerfile.debian.testing and Dockerfile.ubuntu.bionic differ only by cmake and readline versions. Is that the intent? Do we need both?
> 
> It's not particularly worth it to try and generate or abstract the dockerfiles. I would say this is a case of things being very simliar but not the same.

@yashton, I think that the naming is misleading now. You changed it to be based on Ubuntu Bionic, but the name is still `*.debian.testing`: https://github.com/lnis-uofu/LSOracle/blob/master/Dockerfile.debian.testing#L5. There should be two files named `Dockerfile.ubuntu.bionic`, and one or both should have something appended for telling them apart.

> BTW - Rather than generating your own containers, it would be really awesome if LSOracle was packaged and included in the containers generated by hdl/containers (@umarcor).

@mithro, it's ok for each project to have their own containers for internal usage, because we cannot afford to do tight tracking of every tool (yet). There is a comment explaining that `Dockerfile.debian.testing` is primarily meant for CI: https://github.com/lnis-uofu/LSOracle/blob/master/Dockerfile.debian.testing#L1-L3. That is something we do in [ghdl/docker](https://github.com/ghdl/docker) (for testing each commit on Debian, Ubuntu, Fedora, CentOS, Arch, etc.) or in [google/verible](https://github.com/google/verible/tree/master/releasing) (for testing on Ubuntu and CentOS).

However, IMHO those containers should not be advertised for general usage. Instead, it should be suggested for users to consume the ones from hdl/containers. There, we will typically have a single container for each tool (in each collection), rather than covering all possible platforms/distros. Then, the container based testing in this repo allows/will allow foreseeing the issues.

Therefore, I would be interested in picking just one of the dockerfiles in this repo and adapting it to hdl/containers. The main issue I see is that we have two collections at the moment: Debian Buster, and CentOS 7. Here, Debian was used, but this PR changed everything to Ubuntu. @yashton is there any problem with Debian which prevents LSOracle from being used? Or did you change to Ubuntu just because of some personal prefernce?

**Comment by yashton** [comment]
> @yashton, I think that the naming is misleading now. You changed it to be based on Ubuntu Bionic, but the name is still `*.debian.testing`: https://github.com/lnis-uofu/LSOracle/blob/master/Dockerfile.debian.testing#L5. There should be two files named `Dockerfile.ubuntu.bionic`, and one or both should have something appended for telling them apart.

My mistake, i must have overwritten the debian dockerfile, it is obviously not supposed to be ubuntu.

**Comment by umarcor** [comment]
Uh, I'm sorry on your side, but I'm glad to know that, because it makes easier to then adapt it to hdl/containers :wink:

**Pull request merged**
